# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 529a6119bc7213aa5caa7665ff97d8c54ff39d9c73f8729c7c5da0cf482f628e3968af80c06ebb0a38e84118158f316a219287a92881cdbe744cd2e86d75981e

test:
  secret_key_base: 5d5c7b8f90372e77eac81639c5103b127b796fa410e44b592c2d5f708b3a2c249796837a7d2af90ba39b39d4c7311440a0443d3709f8282b8b95b78823ba5025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
